version: '3'

services:

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306  # MySQL 포트 매핑 (호스트 포트:컨테이너 포트)
    environment:
      - MYSQL_ROOT_PASSWORD=0000  # MySQL 루트 비밀번호
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 볼륨


  app:
    build: .
    ports:
      - 8080:8080  # 스프링 애플리케이션의 포트 매핑 (호스트 포트:컨테이너 포트)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bootex?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=0000
    depends_on:
      - mysql


volumes:
  mysql_data:  # MySQL 데이터를 위한 볼륨
